version: "3.7"

services:
  eventbus:
    image: brewblox/mosquitto:develop
    labels:
      - traefik.http.services.eventbus.loadbalancer.server.port=15675
    ports:
      - "1883:1883"

  victoria:
    image: victoriametrics/victoria-metrics:v1.88.0
    labels:
      - traefik.http.services.victoria.loadbalancer.server.port=8428
    command: --envflag.enable=true --envflag.prefix=VM_
    environment:
      - VM_retentionPeriod=100y
      - VM_influxMeasurementFieldSeparator=/
      - VM_http_pathPrefix=/victoria
      - VM_search_latencyOffset=10s
    volumes:
      - type: bind
        source: ./victoria
        target: /victoria-metrics-data

  redis:
    image: redis:6.0
    labels:
      - traefik.enable=false
    volumes:
      - type: bind
        source: ./redis
        target: /data
    command: --appendonly yes

  history:
    build: .
    volumes:
      - type: bind
        source: ./brewblox_history
        target: /app/brewblox_history
      - type: bind
        source: ./parse_appenv.py
        target: /app/parse_appenv.py
      - type: bind
        source: ./entrypoint.sh
        target: /app/entrypoint.sh
    environment:
      - UVICORN_RELOAD=True
      - BREWBLOX_HISTORY_DEBUG=True
    command: --unknown=flappy
    ports:
      - "5000:5000"
