version: "3.7"

services:
  eventbus:
    image: brewblox/mosquitto:develop
    labels:
      - traefik.http.services.eventbus.loadbalancer.server.port=15675
    ports:
      - "1883:1883"

  victoria:
    image: victoriametrics/victoria-metrics:v1.88.0
    labels:
      - traefik.http.services.victoria.loadbalancer.server.port=8428
    volumes:
      - type: bind
        source: ./victoria
        target: /victoria-metrics-data
    command: >-
      --retentionPeriod=100y
      --influxMeasurementFieldSeparator=/
      --http.pathPrefix=/victoria
      --search.latencyOffset=10s

  redis:
    image: redis:6.0
    labels:
      - traefik.enable=false
    volumes:
      - type: bind
        source: ./redis
        target: /data
    command: --appendonly yes

  history:
    build: .
    volumes:
      - type: bind
        source: ./brewblox_history
        target: /app/brewblox_history
      - type: bind
        source: ./parse_appenv.py
        target: /app/parse_appenv.py
    environment:
      - BREWBLOX_DEBUG=True
      - UVICORN_RELOAD=True
    command: --unknown=flappy
    ports:
      - "5000:5000"
