[tool.poetry]
name = "brewblox-history"
version = "0.9.0"
description = "Connector service for Brewblox history data"
authors = ["BrewPi <development@brewpi.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4"
brewblox-service = ">=1.0.0"
aioredis = "^2.0.1"
ciso8601 = "^2.2.0"
pytimeparse = "^1.1.8"

[tool.poetry.dev-dependencies]
pytest-flake8 = "*"
pytest-cov = "*"
pytest-mock = "*"
pytest-aiohttp = "*"
flake8 = "*"
autopep8 = "*"
flake8-quotes = "*"
aresponses = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
