[tool.poetry]
name = "brewblox-history"
version = "1.0.0"
description = "Connector service for Brewblox history data"
authors = ["BrewPi <development@brewpi.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4"
brewblox-service = "^2.1.0"
aioredis = "^2.0.1"
ciso8601 = "^2.2.0"
pytimeparse = "^1.1.8"
llist = "^0.7.1"
cryptography = "41.0.0"

[tool.poetry.dev-dependencies]
pytest-cov = "*"
pytest-mock = "*"
pytest-aiohttp = "*"
flake8 = "*"
autopep8 = "*"
flake8-quotes = "*"
aresponses = "*"
pytest = "*"

[build-system]
requires = ["poetry>=0.12", "cryptography==41.0.0"]
build-backend = "poetry.masonry.api"
