[tool.poetry]
name = "brewblox-history"
version = "0.9.0"
description = "Connector service for Brewblox history data"
authors = ["BrewPi <development@brewpi.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4"
brewblox-service = "^0.33.0"
aioredis = "^1.3.1"
ciso8601 = "^2.1.3"
pytimeparse = "^1.1.8"
marshmallow = "~3.12.0"

[tool.poetry.dev-dependencies]
pytest-flake8 = "^1.0.7"
pytest-cov = "^2.11.1"
pytest-mock = "^3.5.1"
pytest-aiohttp = "^0.3.0"
flake8 = "^3.8.4"
autopep8 = "^1.5.5"
flake8-quotes = "^3.2.0"
aresponses = "^2.1.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
