[tool.poetry]
name = "brewblox-history"
version = "0.9.0"
description = "Connector service for Brewblox history data"
authors = ["BrewPi <development@brewpi.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7"
brewblox-service = "^0.25.0"
aioinflux = "^0.9.0"
dpath = "^2.0.1"
aiohttp-sse = "^2.0.0"
python-dateutil = "^2.8.1"
pytimeparse = "^1.1.8"

[tool.poetry.dev-dependencies]
pytest-flake8 = "^1.0.4"
pytest-cov = "^2.8.1"
pytest-mock = "^2.0.0"
pytest-aiohttp = "^0.3.0"
flake8 = "^3.7.9"
autopep8 = "^1.5"
brewblox-dev = "^1.4.0"
flake8-quotes = "^3.0.0"
asyncmock = "^0.4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
